### ISSUE TITLE
Set up a debateco.re website repository

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/.github#4]
Set up a repository with to store the [debateco.re](https://debateco.re) website in.

**Comment by jakubmanczak** [comment]
Are we sure we need this level of granularity? I deem it kind of obvious that there would be a repository holding the website code ( – when there's code to be held, outside a placeholder two lines with colouring).

**Comment by jakubmanczak** [comment]
Side note: the project board is marked as private, but issues on a public repository are inherently public.

**Comment by Mateusz-Dobrzynski** [comment]
That's a fair point, this might've been too obvious to make an issue out of it.
